[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_market = "7JAt2fYYm4L9ZYTeZiN3j7eQtUGwCHiCjk9gn3MEfx55"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
